name: Update Staging App

on:
  workflow_dispatch:
  push:
    branches:
      - stg/*

jobs:
  android:
    name: Build Android App
    runs-on: ubuntu-latest
    environment:
      name: android
      url: ${{ steps.deployments.outputs.alias }}

    outputs:
      FIREBASE_TOKEN: ${{ steps.set-secrets.outputs.FIREBASE_TOKEN }}
      ANDROID_KEYSTORE: ${{ steps.set-secrets.outputs.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ steps.set-secrets.outputs.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ steps.set-secrets.outputs.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ steps.set-secrets.outputs.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout Partner repository
        uses: actions/checkout@v4.1.7
        with:
          repository: indipe-paytech/indipe-partner-app
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Get Partner Details
        id: partners
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://mocki.io/v1/85309399-d332-4720-85c9-09dd53625940'
          method: 'GET'

      - name: Download Assets
        run: |
          assets=$(echo '${{ steps.partners.outputs.response }}' | jq -c '.assets[]')
          cd packages/app/assets/logos/
          rm -rf *
          for asset in $assets; do
            url=$(echo $asset | jq -r '.url')
            name=$(echo $asset | jq -r '.name')
            file=$(basename "$url")
            wget -nc $url

            if [ "$file" != "$name" ]; then
              mv $file $name
            fi
          done
          cd ../../../..
        shell: bash

      - name: Set Secret Environment Variables from API Response
        id: set-secrets
        run: |
          partner=$(echo '${{ steps.partners.outputs.response }}' | jq -r '.')
          echo "FIREBASE_TOKEN=$(echo $partner | jq -r '.firebase_token')" >> $GITHUB_OUTPUT
          echo "ANDROID_KEYSTORE=$(echo $partner | jq -r '.keystore')" >> $GITHUB_OUTPUT
          echo "ANDROID_KEYSTORE_PASSWORD=$(echo $partner | jq -r '.keystore_password')" >> $GITHUB_OUTPUT
          echo "ANDROID_KEY_ALIAS=$(echo $partner | jq -r '.key_alias')" >> $GITHUB_OUTPUT
          echo "ANDROID_KEY_PASSWORD=$(echo $partner | jq -r '.key_password')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Current State
        id: current-state
        uses: actions/cache/save@v4.0.2
        with:
          path: ./*
          key: ${{ runner.os }}-app-${{ github.ref }}

  build-android:
    needs: android
    uses: indipe-paytech/shared-mobile-workflows/.github/workflows/build.yml@main
    with:
      ENVIRONMENT: STAGING_ENV
      DOPPLER_CONFIG: dev
      APP_VERSION: 0.0.${{ github.run_number }}
      APP_NUMBER: $(( ${{ github.run_number }} + 55 ))
      SKIP_CHECKOUT: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      FIREBASE_TOKEN: ${{ needs.android.outputs.FIREBASE_TOKEN }}
      ANDROID_KEYSTORE: ${{ needs.android.outputs.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ needs.android.outputs.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ needs.android.outputs.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ needs.android.outputs.ANDROID_KEY_PASSWORD }}

  delete-cache:
    needs: build-android
    name: Delete Cache
    runs-on: ubuntu-latest
    steps:
      - name: Delete Cache
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/caches?key=${{ runner.os }}-app-${{ github.ref }}
